const sampleData=[['2026-01-02','Indigo Airlines','Travel',12450],['2026-01-04','BigBasket','Groceries',2140],['2026-01-05','Netflix','Subscriptions',649],['2026-01-06','Apollo Pharmacy','Healthcare',920],['2026-01-09','Uber','Transport',410],['2026-01-11','Amazon Electronics','Electronics',18990],['2026-01-12','Electricity Bill','Utilities',3860],['2026-01-16','Swiggy','Dining',740],['2026-01-19','Udemy Course','Education',799],['2026-01-22','Zara','Shopping',4290],['2026-01-24','Movie Tickets','Entertainment',980],['2026-01-28','Rent','Housing',18500],['2026-02-02','Fuel Station','Transport',3150],['2026-02-05','Spotify','Subscriptions',119],['2026-02-08','Doctor Visit','Healthcare',1500],['2026-02-12','Taj Hotel','Travel',9600],['2026-02-14','Cafe Dinner','Dining',1860],['2026-02-18','Myntra','Shopping',2590],['2026-02-21','Water Bill','Utilities',620],['2026-02-24','Coursera','Education',3999],['2026-02-27','Airbnb','Travel',14300],['2026-03-01','Grocery Mart','Groceries',1980],['2026-03-03','Prime Video','Subscriptions',299],['2026-03-07','Dental Care','Healthcare',4100],['2026-03-12','Croma','Electronics',23990],['2026-03-16','Restaurant','Dining',2200],['2026-03-18','Metro Card','Transport',1000],['2026-03-21','Internet Bill','Utilities',999],['2026-03-25','Book Store','Education',650],['2026-03-28','Concert','Entertainment',3400]];
const personas=[
{name:'Big Ticket Buyer',label:'High-Value Discretionary Spender',cats:['Travel','Shopping','Electronics'],color:'#4d8dff',advice:'Create a sinking fund for large planned purchases and set approval rules for discretionary spends above ₹10,000.'},
{name:'Essentials Optimizer',label:'Frugal Essentials Spender',cats:['Groceries','Utilities','Healthcare','Housing'],color:'#1dd8d1',advice:'Your essentials are stable. Improve rewards by routing recurring bills through cashback or utility-friendly cards.'},
{name:'Subscription Accumulator',label:'Fixed Subscription Spender',cats:['Subscriptions','Entertainment','Education'],color:'#8b5cf6',advice:'Audit subscriptions every 30 days. Cancel unused services and combine overlapping entertainment platforms.'},
{name:'Lifestyle Drifter',label:'Impulse Lifestyle Spender',cats:['Dining','Transport'],color:'#f59e0b',advice:'Use weekly dining and commute limits. Small frequent transactions can quietly reduce monthly savings.'}
];
let transactions=[];let activeTab='scatter';
const fmt=n=>'₹'+Math.round(n).toLocaleString('en-IN');
function parseCSV(text){return text.trim().split(/\r?\n/).slice(1).map(r=>{const p=r.split(',').map(x=>x.trim().replace(/^"|"$/g,''));return [p[0],p[1],p[2],Number(p[3])||0]}).filter(r=>r[3]>0)}
function classify(t){const cat=t[2];let idx=personas.findIndex(p=>p.cats.includes(cat));if(idx<0)idx=t[3]>8000?0:3;return idx;}
function analyze(){if(!transactions.length)transactions=[...sampleData];const total=transactions.reduce((s,t)=>s+t[3],0),avg=total/transactions.length;const sd=Math.sqrt(transactions.reduce((s,t)=>s+(t[3]-avg)**2,0)/transactions.length);const anomalies=transactions.filter(t=>t[3]>avg+sd*1.15).length;document.getElementById('totalVolume').textContent=fmt(total);document.getElementById('txnCount').textContent=transactions.length+' transactions';document.getElementById('avgTxn').textContent=fmt(avg);document.getElementById('anomalyCount').textContent=anomalies;const counts=[0,0,0,0];transactions.forEach(t=>counts[classify(t)]++);const dominant=counts.indexOf(Math.max(...counts));document.getElementById('dominantPersona').textContent=personas[dominant].name;renderChart();renderInsights();}
function renderInsights(){const grid=document.getElementById('insightGrid');grid.innerHTML='';personas.forEach((p,i)=>{const tx=transactions.filter(t=>classify(t)===i),sum=tx.reduce((s,t)=>s+t[3],0),avg=tx.length?sum/tx.length:0,share=transactions.length?sum/transactions.reduce((s,t)=>s+t[3],0)*100:0;grid.innerHTML+=`<article class="insight-card glass-card" style="--accent:${p.color}"><div class="insight-title"><span class="dot"></span><div><h3>${p.name}</h3><span class="tag">${p.label}</span></div></div><div class="insight-meta">${share.toFixed(1)}% of volume • ${tx.length} txns • Avg ${fmt(avg)}</div><div class="chips">${p.cats.slice(0,4).map(c=>`<span>${c}</span>`).join('')}</div><div class="analysis-box"><b>Analysis</b>${tx.length?`This cluster captures ${p.cats.join(', ')} spending with ${tx.length} transactions and a total of ${fmt(sum)}. It reveals a clear pattern in your monthly financial behavior.`:'No transactions currently mapped to this persona.'}</div><div class="advice-box"><b>Strategic advice</b>${p.advice}</div></article>`})}
function drawAxes(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.09)';ctx.lineWidth=1;for(let i=0;i<8;i++){let x=70+i*(w-120)/7;ctx.beginPath();ctx.moveTo(x,30);ctx.lineTo(x,h-55);ctx.stroke()}for(let i=0;i<6;i++){let y=40+i*(h-100)/5;ctx.beginPath();ctx.moveTo(60,y);ctx.lineTo(w-40,y);ctx.stroke()}ctx.fillStyle='#9aa8bd';ctx.font='14px Inter';ctx.fillText(activeTab==='scatter'?'Transaction amount vs spending frequency':'Spending distribution',70,25)}
function renderChart(){const c=document.getElementById('mainChart'),ctx=c.getContext('2d'),w=c.width,h=c.height;drawAxes(ctx,w,h);if(activeTab==='scatter'){const max=Math.max(...transactions.map(t=>t[3]),1);transactions.forEach((t,i)=>{const group=classify(t),x=80+(t[3]/max)*(w-170)+Math.sin(i)*22,y=60+((i%14)/14)*(h-140)+Math.cos(t[3])*35;ctx.fillStyle=personas[group].color;ctx.globalAlpha=.86;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;personas.forEach((p,i)=>{ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(w-190,70+i*28,7,0,7);ctx.fill();ctx.fillStyle='#f5f8ff';ctx.fillText(p.name,w-172,75+i*28)})}
else if(activeTab==='breakdown'){const sums=[0,0,0,0];transactions.forEach(t=>sums[classify(t)]+=t[3]);const max=Math.max(...sums,1);sums.forEach((s,i)=>{const y=75+i*85;ctx.fillStyle='rgba(255,255,255,.06)';ctx.fillRect(85,y,w-210,34);ctx.fillStyle=personas[i].color;ctx.fillRect(85,y,(s/max)*(w-210),34);ctx.fillStyle='#fff';ctx.fillText(personas[i].name,90,y-10);ctx.fillText(fmt(s),w-150,y+23)})}
else{const cats=[...new Set(transactions.map(t=>t[2]))].slice(0,10);const max=Math.max(...transactions.map(t=>t[3]),1);cats.forEach((cat,i)=>{for(let m=0;m<6;m++){const v=transactions.filter((t,idx)=>t[2]===cat&&idx%6===m).reduce((s,t)=>s+t[3],0);ctx.fillStyle=`rgba(29,216,209,${Math.min(.12+v/max,.95)})`;ctx.fillRect(90+m*115,55+i*40,92,28)}ctx.fillStyle='#d8e1ee';ctx.fillText(cat,730,75+i*40)})}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeTab=b.dataset.tab;renderChart()});
document.getElementById('sampleBtn').onclick=document.getElementById('heroSampleBtn').onclick=()=>{transactions=[...sampleData];document.getElementById('dataStatus').textContent='Sample data loaded';analyze()};
document.getElementById('runBtn').onclick=analyze;document.getElementById('optimalBtn').onclick=()=>{document.getElementById('kSlider').value=4;document.getElementById('kValue').textContent=4;document.getElementById('dataStatus').textContent='Optimal K found: 4'};document.getElementById('kSlider').oninput=e=>document.getElementById('kValue').textContent=e.target.value;document.getElementById('csvInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{transactions=parseCSV(reader.result);document.getElementById('dataStatus').textContent=file.name+' loaded';analyze()};reader.readAsText(file)};document.getElementById('downloadCsvBtn').onclick=()=>{const csv='date,description,category,amount\n'+sampleData.map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='finintelligence_sample.csv';a.click()};transactions=[...sampleData];analyze();
